/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pro_msg_ProMsgJni */

#ifndef _Included_com_pro_msg_ProMsgJni
#define _Included_com_pro_msg_ProMsgJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    getVersion
 * Signature: ([S[S[S)V
 */
JNIEXPORT void JNICALL Java_com_pro_msg_ProMsgJni_getVersion
  (JNIEnv *, jclass, jshortArray, jshortArray, jshortArray);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    init
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pro_msg_ProMsgJni_init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    fini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pro_msg_ProMsgJni_fini
  (JNIEnv *, jclass);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientCreate
 * Signature: (Lcom/pro/msg/ProMsgJni/MsgClientListener;Ljava/lang/String;SLjava/lang/String;ILcom/pro/msg/ProMsgJni/PRO_MSG_USER;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_pro_msg_ProMsgJni_msgClientCreate
  (JNIEnv *, jclass, jobject, jstring, jshort, jstring, jint, jobject, jstring, jstring);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pro_msg_ProMsgJni_msgClientDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientGetUser
 * Signature: (J)Lcom/pro/msg/ProMsgJni/PRO_MSG_USER;
 */
JNIEXPORT jobject JNICALL Java_com_pro_msg_ProMsgJni_msgClientGetUser
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientGetSslSuite
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pro_msg_ProMsgJni_msgClientGetSslSuite
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientGetLocalIp
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pro_msg_ProMsgJni_msgClientGetLocalIp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientGetLocalPort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_pro_msg_ProMsgJni_msgClientGetLocalPort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientGetRemoteIp
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pro_msg_ProMsgJni_msgClientGetRemoteIp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientGetRemotePort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_pro_msg_ProMsgJni_msgClientGetRemotePort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientSendMsg
 * Signature: (J[BI[Lcom/pro/msg/ProMsgJni/PRO_MSG_USER;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pro_msg_ProMsgJni_msgClientSendMsg
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobjectArray);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientSetOutputRedline
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_pro_msg_ProMsgJni_msgClientSetOutputRedline
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgClientGetOutputRedline
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pro_msg_ProMsgJni_msgClientGetOutputRedline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgServerCreate
 * Signature: (Lcom/pro/msg/ProMsgJni/MsgServerListener;Ljava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL Java_com_pro_msg_ProMsgJni_msgServerCreate
  (JNIEnv *, jclass, jobject, jstring, jshort);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgServerDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pro_msg_ProMsgJni_msgServerDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgServerGetUserCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pro_msg_ProMsgJni_msgServerGetUserCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgServerKickoutUser
 * Signature: (JLcom/pro/msg/ProMsgJni/PRO_MSG_USER;)V
 */
JNIEXPORT void JNICALL Java_com_pro_msg_ProMsgJni_msgServerKickoutUser
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgServerSendMsg
 * Signature: (J[BI[Lcom/pro/msg/ProMsgJni/PRO_MSG_USER;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pro_msg_ProMsgJni_msgServerSendMsg
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobjectArray);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgServerSetOutputRedline
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_pro_msg_ProMsgJni_msgServerSetOutputRedline
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_pro_msg_ProMsgJni
 * Method:    msgServerGetOutputRedline
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_pro_msg_ProMsgJni_msgServerGetOutputRedline
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
